services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mishcredit_net
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - mishcredit_net
  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - mishcredit_net
volumes:
  mongo_data: {}

networks:
  mishcredit_net:
    driver: bridge
